// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.4.7.
// **********************************************************************

#ifndef __JAVA2ROOMPROTO_H_
#define __JAVA2ROOMPROTO_H_

#include <map>
#include <string>
#include <vector>
#include "tup/Tars.h"
#include "tup/TarsJson.h"
using namespace std;


namespace java2room
{
    enum Eum_Msgid
    {
        E_MSGID_CLUB_ROOM_CONFIG_CHANGE_NOTIFY = 20000,
        E_MSGID_CLUB_ROOM_DISMISS_NOTIFY = 20001,
        E_MSGID_USER_ACCOUNT_GOLD_CHANGE_NOTIFY = 20051,
        E_MSGID_JACKPOT_MODIFY_NOTIFY = 20100,
    };
    inline string etos(const Eum_Msgid & e)
    {
        switch(e)
        {
            case E_MSGID_CLUB_ROOM_CONFIG_CHANGE_NOTIFY: return "E_MSGID_CLUB_ROOM_CONFIG_CHANGE_NOTIFY";
            case E_MSGID_CLUB_ROOM_DISMISS_NOTIFY: return "E_MSGID_CLUB_ROOM_DISMISS_NOTIFY";
            case E_MSGID_USER_ACCOUNT_GOLD_CHANGE_NOTIFY: return "E_MSGID_USER_ACCOUNT_GOLD_CHANGE_NOTIFY";
            case E_MSGID_JACKPOT_MODIFY_NOTIFY: return "E_MSGID_JACKPOT_MODIFY_NOTIFY";
            default: return "";
        }
    }
    inline int stoe(const string & s, Eum_Msgid & e)
    {
        if(s == "E_MSGID_CLUB_ROOM_CONFIG_CHANGE_NOTIFY")  { e=E_MSGID_CLUB_ROOM_CONFIG_CHANGE_NOTIFY; return 0;}
        if(s == "E_MSGID_CLUB_ROOM_DISMISS_NOTIFY")  { e=E_MSGID_CLUB_ROOM_DISMISS_NOTIFY; return 0;}
        if(s == "E_MSGID_USER_ACCOUNT_GOLD_CHANGE_NOTIFY")  { e=E_MSGID_USER_ACCOUNT_GOLD_CHANGE_NOTIFY; return 0;}
        if(s == "E_MSGID_JACKPOT_MODIFY_NOTIFY")  { e=E_MSGID_JACKPOT_MODIFY_NOTIFY; return 0;}

        return -1;
    }

    struct NotifyRoomReq : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "java2room.NotifyRoomReq";
        }
        static string MD5()
        {
            return "cca41655ef02173a34fb6fd7b66ff38e";
        }
        NotifyRoomReq()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            messageId = 0;
            roomId = "";
            relateId = "";
            extraInfo = "";
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(messageId, 0);
            _os.write(roomId, 1);
            _os.write(relateId, 2);
            _os.write(extraInfo, 3);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(messageId, 0, true);
            _is.read(roomId, 1, true);
            _is.read(relateId, 2, true);
            _is.read(extraInfo, 3, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["messageId"] = tars::JsonOutput::writeJson(messageId);
            p->value["roomId"] = tars::JsonOutput::writeJson(roomId);
            p->value["relateId"] = tars::JsonOutput::writeJson(relateId);
            p->value["extraInfo"] = tars::JsonOutput::writeJson(extraInfo);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(messageId,pObj->value["messageId"], true);
            tars::JsonInput::readJson(roomId,pObj->value["roomId"], true);
            tars::JsonInput::readJson(relateId,pObj->value["relateId"], true);
            tars::JsonInput::readJson(extraInfo,pObj->value["extraInfo"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(messageId,"messageId");
            _ds.display(roomId,"roomId");
            _ds.display(relateId,"relateId");
            _ds.display(extraInfo,"extraInfo");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(messageId, true);
            _ds.displaySimple(roomId, true);
            _ds.displaySimple(relateId, true);
            _ds.displaySimple(extraInfo, false);
            return _os;
        }
    public:
        tars::Int32 messageId;
        std::string roomId;
        std::string relateId;
        std::string extraInfo;
    };
    inline bool operator==(const NotifyRoomReq&l, const NotifyRoomReq&r)
    {
        return l.messageId == r.messageId && l.roomId == r.roomId && l.relateId == r.relateId && l.extraInfo == r.extraInfo;
    }
    inline bool operator!=(const NotifyRoomReq&l, const NotifyRoomReq&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const NotifyRoomReq&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,NotifyRoomReq&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }


}



#endif
