// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.4.7.
// **********************************************************************

#ifndef __JFGAME_H_
#define __JFGAME_H_

#include <map>
#include <string>
#include <vector>
#include "tup/Tars.h"
#include "tup/TarsJson.h"
using namespace std;


namespace JFGame
{
    struct TClientParam : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "JFGame.TClientParam";
        }
        static string MD5()
        {
            return "f7b89797fc79cd578654d9c7e27d4988";
        }
        TClientParam()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            sAddr = "";
            nPort = 0;
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(sAddr, 0);
            _os.write(nPort, 1);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(sAddr, 0, true);
            _is.read(nPort, 1, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["sAddr"] = tars::JsonOutput::writeJson(sAddr);
            p->value["nPort"] = tars::JsonOutput::writeJson(nPort);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(sAddr,pObj->value["sAddr"], true);
            tars::JsonInput::readJson(nPort,pObj->value["nPort"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(sAddr,"sAddr");
            _ds.display(nPort,"nPort");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(sAddr, true);
            _ds.displaySimple(nPort, false);
            return _os;
        }
    public:
        std::string sAddr;
        tars::Short nPort;
    };
    inline bool operator==(const TClientParam&l, const TClientParam&r)
    {
        return l.sAddr == r.sAddr && l.nPort == r.nPort;
    }
    inline bool operator!=(const TClientParam&l, const TClientParam&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const TClientParam&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,TClientParam&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct UserBaseInfoExt : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "JFGame.UserBaseInfoExt";
        }
        static string MD5()
        {
            return "b0295989dbf7904c1b79325151e91f5d";
        }
        UserBaseInfoExt()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            num = 0;
            deviceID = "";
            deviceType = "";
            platform = 0;
            channnelID = 0;
            areaID = 0;
            isRobot = 0;
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(num, 0);
            if (deviceID != "")
            {
                _os.write(deviceID, 1);
            }
            if (deviceType != "")
            {
                _os.write(deviceType, 2);
            }
            if (platform != 0)
            {
                _os.write(platform, 3);
            }
            if (channnelID != 0)
            {
                _os.write(channnelID, 4);
            }
            if (areaID != 0)
            {
                _os.write(areaID, 5);
            }
            if (isRobot != 0)
            {
                _os.write(isRobot, 6);
            }
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(num, 0, true);
            _is.read(deviceID, 1, false);
            _is.read(deviceType, 2, false);
            _is.read(platform, 3, false);
            _is.read(channnelID, 4, false);
            _is.read(areaID, 5, false);
            _is.read(isRobot, 6, false);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["num"] = tars::JsonOutput::writeJson(num);
            p->value["deviceID"] = tars::JsonOutput::writeJson(deviceID);
            p->value["deviceType"] = tars::JsonOutput::writeJson(deviceType);
            p->value["platform"] = tars::JsonOutput::writeJson(platform);
            p->value["channnelID"] = tars::JsonOutput::writeJson(channnelID);
            p->value["areaID"] = tars::JsonOutput::writeJson(areaID);
            p->value["isRobot"] = tars::JsonOutput::writeJson(isRobot);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(num,pObj->value["num"], true);
            tars::JsonInput::readJson(deviceID,pObj->value["deviceID"], false);
            tars::JsonInput::readJson(deviceType,pObj->value["deviceType"], false);
            tars::JsonInput::readJson(platform,pObj->value["platform"], false);
            tars::JsonInput::readJson(channnelID,pObj->value["channnelID"], false);
            tars::JsonInput::readJson(areaID,pObj->value["areaID"], false);
            tars::JsonInput::readJson(isRobot,pObj->value["isRobot"], false);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(num,"num");
            _ds.display(deviceID,"deviceID");
            _ds.display(deviceType,"deviceType");
            _ds.display(platform,"platform");
            _ds.display(channnelID,"channnelID");
            _ds.display(areaID,"areaID");
            _ds.display(isRobot,"isRobot");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(num, true);
            _ds.displaySimple(deviceID, true);
            _ds.displaySimple(deviceType, true);
            _ds.displaySimple(platform, true);
            _ds.displaySimple(channnelID, true);
            _ds.displaySimple(areaID, true);
            _ds.displaySimple(isRobot, false);
            return _os;
        }
    public:
        tars::Int32 num;
        std::string deviceID;
        std::string deviceType;
        tars::Int32 platform;
        tars::Int32 channnelID;
        tars::Int32 areaID;
        tars::Int32 isRobot;
    };
    inline bool operator==(const UserBaseInfoExt&l, const UserBaseInfoExt&r)
    {
        return l.num == r.num && l.deviceID == r.deviceID && l.deviceType == r.deviceType && l.platform == r.platform && l.channnelID == r.channnelID && l.areaID == r.areaID && l.isRobot == r.isRobot;
    }
    inline bool operator!=(const UserBaseInfoExt&l, const UserBaseInfoExt&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const UserBaseInfoExt&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,UserBaseInfoExt&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }


}



#endif
